apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: us-east1-docker.pkg.dev/terraform-project-iti/tf-gcp/hello-world-app:v1
          ports:
            - containerPort: 3000