apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: us-east1-docker.pkg.dev/final-devops-iti/tf-gcp/hello-world-app:v1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000